{
   "jobs" : {
      "build" : {
         "environment" : {
            "CIRCLE_ARTIFACTS" : "/tmp/circle-artifacts/build"
         },
         "machine" : {
            "image" : "ubuntu-2004:202101-01"
         },
         "steps" : [
            "checkout",
            {
               "run" : {
                  "command" : "mkdir -p $CIRCLE_ARTIFACTS"
               }
            },
            {
               "run" : {
                  "command" : "git submodule update --init"
               }
            },
            {
               "run" : {
                  "command" : "rm -fr modules/*/bin modules/*/.git modules/*/t modules/*/t_deps"
               }
            },
            {
               "run" : {
                  "command" : "mv config/Dockerfile ./"
               }
            },
            {
               "run" : {
                  "command" : "git rev-parse HEAD > rev"
               }
            },
            {
               "run" : {
                  "command" : "docker info"
               }
            },
            {
               "run" : {
                  "command" : "docker build -t quay.io/wakaba/swchars ."
               }
            },
            {
               "run" : {
                  "command" : "docker run --name server -d -p 5511:8080 quay.io/wakaba/swchars /server; sleep 10"
               }
            },
            {
               "run" : {
                  "command" : "curl -f http://localhost:5511"
               }
            },
            {
               "run" : {
                  "command" : "curl -f http://localhost:5511/char/1234"
               }
            },
            {
               "run" : {
                  "command" : "curl -f http://localhost:5511/css"
               }
            },
            {
               "run" : {
                  "command" : "curl -f http://localhost:5511/fonts/mona.ttf > $CIRCLE_ARTIFACTS/mona.ttf"
               }
            },
            {
               "run" : {
                  "command" : "docker logs server"
               }
            },
            {
               "store_artifacts" : {
                  "path" : "/tmp/circle-artifacts/build"
               }
            },
            {
               "deploy" : {
                  "command" : "if [ \u0022${CIRCLE_BRANCH}\u0022 == 'master' ]; then\u000Atrue\u000Adocker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS quay.io || docker login -u $DOCKER_USER -p $DOCKER_PASS quay.io\u000Afi"
               }
            },
            {
               "deploy" : {
                  "command" : "if [ \u0022${CIRCLE_BRANCH}\u0022 == 'master' ]; then\u000Atrue\u000Adocker push quay.io/wakaba/swchars && curl -sSLf $BWALL_URL -X POST\u000Afi"
               }
            }
         ]
      },
      "deploy_nightly" : {
         "machine" : {
            "image" : "ubuntu-2004:202101-01"
         },
         "steps" : [
            "checkout",
            {
               "deploy" : {
                  "command" : "git rev-parse HEAD > head.txt\u000Acurl -f -s -S --request POST --header \u0022Authorization:token $GITHUB_ACCESS_TOKEN\u0022 --header \u0022Content-Type:application/json\u0022 --data-binary \u0022{\u005C\u0022base\u005C\u0022:\u005C\u0022master\u005C\u0022,\u005C\u0022head\u005C\u0022:\u005C\u0022`cat head.txt`\u005C\u0022,\u005C\u0022commit_message\u005C\u0022:\u005C\u0022auto-merge $CIRCLE_BRANCH into master\u005C\u0022}\u0022 \u0022https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/merges\u0022 && curl -f https://$BWALL_TOKEN:@$BWALL_HOST/ping/merger.$CIRCLE_BRANCH/$CIRCLE_PROJECT_USERNAME%2F$CIRCLE_PROJECT_REPONAME -X POST"
               }
            }
         ]
      },
      "deploy_staging" : {
         "machine" : {
            "image" : "ubuntu-2004:202101-01"
         },
         "steps" : [
            "checkout",
            {
               "deploy" : {
                  "command" : "git rev-parse HEAD > head.txt\u000Acurl -f -s -S --request POST --header \u0022Authorization:token $GITHUB_ACCESS_TOKEN\u0022 --header \u0022Content-Type:application/json\u0022 --data-binary \u0022{\u005C\u0022base\u005C\u0022:\u005C\u0022master\u005C\u0022,\u005C\u0022head\u005C\u0022:\u005C\u0022`cat head.txt`\u005C\u0022,\u005C\u0022commit_message\u005C\u0022:\u005C\u0022auto-merge $CIRCLE_BRANCH into master\u005C\u0022}\u0022 \u0022https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/merges\u0022 && curl -f https://$BWALL_TOKEN:@$BWALL_HOST/ping/merger.$CIRCLE_BRANCH/$CIRCLE_PROJECT_USERNAME%2F$CIRCLE_PROJECT_REPONAME -X POST"
               }
            }
         ]
      },
      "gaa4" : {
         "machine" : {
            "image" : "ubuntu-2004:202101-01"
         },
         "steps" : [
            "checkout",
            {
               "run" : {
                  "command" : "git config --global user.email \u0022temp@circleci.test\u0022;git config --global user.name \u0022CircleCI\u0022"
               }
            },
            {
               "run" : {
                  "command" : "make deps"
               }
            },
            {
               "run" : {
                  "command" : "make updatenightly"
               }
            },
            {
               "deploy" : {
                  "command" : "git diff-index --quiet HEAD --cached || git commit -m auto"
               }
            },
            {
               "deploy" : {
                  "command" : "git push origin \u002B`git rev-parse HEAD`:refs/heads/nightly"
               }
            }
         ]
      }
   },
   "version" : 2,
   "workflows" : {
      "build" : {
         "jobs" : [
            "build",
            {
               "deploy_nightly" : {
                  "context" : [
                     "deploy-context"
                  ],
                  "filters" : {
                     "branches" : {
                        "only" : [
                           "nightly"
                        ]
                     }
                  },
                  "requires" : [
                     "build"
                  ]
               }
            },
            {
               "deploy_staging" : {
                  "context" : [
                     "deploy-context"
                  ],
                  "filters" : {
                     "branches" : {
                        "only" : [
                           "staging"
                        ]
                     }
                  },
                  "requires" : [
                     "build"
                  ]
               }
            }
         ]
      },
      "gaa4" : {
         "jobs" : [
            "gaa4"
         ],
         "triggers" : [
            {
               "schedule" : {
                  "cron" : "20 23 * * *",
                  "filters" : {
                     "branches" : {
                        "only" : [
                           "master"
                        ]
                     }
                  }
               }
            }
         ]
      },
      "version" : 2
   }
}
